INSERT INTO `goods`
(`goods_name`, `goods_tag`, `goods_price`, `goods_flg`, `goods_imgurl1`, `goods_imgurl2`, `goods_imgurl3`, `goods_imgurl4`,`goods_detail`, `goods_createdate`)
VALUES ('ライトウールスカーフ - オーバーサイズ',
        'Acce',
        28600,
        true,
        '../public/img_goods/Acce_1.jpg',
        '../public/img_goods/Acce_1-2.jpg',
        '../public/img_goods/Acce_1-3.jpg',
        '../public/img_goods/Acce_1-4.jpg',
        'Acne Studiosのスカーフ。ライトグレーメランジのソフトな薄手ウールを使用。両端に控えめなフリンジ付き、Acne Studiosのラベルがアクセントに。',
        now()),
VALUES ('フリンジウールスカーフ - オーバーサイズ',
        'Acce',
        26950,
        true,
        '../public/img_goods/Acce_2.jpg',
        '../public/img_goods/Acce_2-2.jpg',
        '../public/img_goods/Acce_2-3.jpg',
        '../public/img_goods/Acce_2-4.jpg',
        'Acne Studiosのフリンジスカーフ。ライトオリーブメランジの中厚ウールを使用。Acne Studiosのピンクラベルがアクセントに。',
        now()),
