INSERT INTO `goods`
(`goods_name`, `goods_tag`, `goods_price`, `goods_flg`, `goods_imgurl1`, `goods_imgurl2`, `goods_imgurl3`, `goods_imgurl4`,`goods_detail`, `goods_createdate`)
VALUES ('ライトウールスカーフ - オーバーサイズ',
        'Acce',
        28600,
        true,
        '../public/img_goods/Acce_1.jpg',
        '../public/img_goods/Acce_1-2.jpg',
        '../public/img_goods/Acce_1-3.jpg',
        '../public/img_goods/Acce_1-4.jpg',
        'Acne Studiosのスカーフ。<br>ライトグレーメランジのソフトな薄手ウールを使用。<br>両端に控えめなフリンジ付き、Acne Studiosのラベルがアクセントに。',
        now()),
        ('フリンジウールスカーフ - オーバーサイズ',
        'Acce',
        26950,
        true,
        '../public/img_goods/Acce_2.jpg',
        '../public/img_goods/Acce_2-2.jpg',
        '../public/img_goods/Acce_2-3.jpg',
        '../public/img_goods/Acce_2-4.jpg',
        'Acne Studiosのフリンジスカーフ。<br>ライトオリーブメランジの中厚ウールを使用。<br>Acne Studiosのピンクラベルがアクセントに。',
        now()),
        ('フリンジウールスカーフ - スキニー',
        'Acce',
        17050,
        true,
        '../public/img_goods/Acce_3.jpg',
        '../public/img_goods/Acce_3-2.jpg',
        '../public/img_goods/Acce_3-3.jpg',
        '../public/img_goods/Acce_3-4.jpg',
        'Acne Studiosのフリンジスカーフ。<br>ネイビーブルーの中厚ウールを使用。<br>Acne Studiosのピンクラベルがアクセントに。',
        now()),
        ('フリンジウールスカーフ - ナロー ',
        'Acce',
        21450,
        true,
        '../public/img_goods/Acce_4.jpg',
        '../public/img_goods/Acce_4-2.jpg',
        '../public/img_goods/Acce_4-3.jpg',
        '../public/img_goods/Acce_4-4.jpg',
        'Acne Studiosのフリンジスカーフ。<br>キャラメルブラウンの中厚ウールを使用。<br>Acne Studiosのピンクラベルがアクセントに。',
        now()),
        ('チェックウールスカーフ ',
        'Acce',
        24200,
        true,
        '../public/img_goods/Acce_5.jpg',
        '../public/img_goods/Acce_5-2.jpg',
        '../public/img_goods/Acce_5-3.jpg',
        '../public/img_goods/Acce_5-4.jpg',
        'Acne Studiosのウールスカーフ。<br>グレー/ブラック/ホワイトのチェック柄をあしらったデザイン。<br>洗濯表示ラベルのプリント入り。',
        now()),
        ('タフテッドウールブレンドスカーフ',
        'Acce',
        44000,
        true,
        '../public/img_goods/Acce_6.jpg',
        '../public/img_goods/Acce_6-2.jpg',
        '../public/img_goods/Acce_6-3.jpg',
        '../public/img_goods/Acce_6-4.jpg',
        'Acne Studiosのニットスカーフ。<br>ソフトでふんわりとした風合いに仕上げたチョコレートブラウンのタフテッドウールブレンド素材を使用。<br>Acne Studiosのロゴラベルがアクセントに。',
        now()),
        ('スモールFACEロゴビーニー',
        'Acce',
        19800,
        true,
        '../public/img_goods/Acce_7.jpg',
        '../public/img_goods/Acce_7-2.jpg',
        '../public/img_goods/Acce_7-3.jpg',
        '../public/img_goods/Acce_7-4.jpg',
        'Acne Studiosのニットビーニー。<br>パープルメランジのチャンキーウールを使用。<br>小さなFaceロゴパッチ刺繍とリブ編みディテールがアクセントに。',
        now()),
        ('スモールFACEロゴビーニー',
        'Acce',
        17050,
        true,
        '../public/img_goods/Acce_8.jpg',
        '../public/img_goods/Acce_8-2.jpg',
        '../public/img_goods/Acce_8-3.jpg',
        '../public/img_goods/Acce_8-4.jpg',
        'Acne Studiosのニットビーニー。<br>グレーメランジのチャンキーウールを使用。<br>小さなFaceロゴパッチ刺繍とリブ編みディテールがアクセントに。',
        now()),
        ('コットン ベースボールキャップ',
        'Acce',
        17050,
        true,
        '../public/img_goods/Acce_9.jpg',
        '../public/img_goods/Acce_9-2.jpg',
        '../public/img_goods/Acce_9-3.jpg',
        '../public/img_goods/Acce_9-4.jpg',
        'Acne Studiosのベースボールキャップ<br>。フォレストグリーンの色合いで、フローラルパターン入りライニングがコントラストを効かせるシックスパネルデザイン。<br>ヘッドバンドに配した調節可能なビニールストラップ、アイレット、マイクロフェイスパッチがアクセントに。<br>主な素材にリサイクルポリエステルと環境にやさしい方法で栽培したコットンを使用。',
        now()),
        ('フランネルバケットハット',
        'Acce',
        18700,
        true,
        '../public/img_goods/Acce_10.jpg',
        '../public/img_goods/Acce_10-2.jpg',
        '../public/img_goods/Acce_10-3.jpg',
        '../public/img_goods/Acce_10-4.jpg',
        'Acne Studiosのバケットハット。<br>オプティックホワイト/ブラックの起毛仕上げフランネル素材を使用した、チェッカーデザイン。<br>環境にやさしい方法で栽培したコットンを使用。<br>フェイスロゴ刺繍パッチとフェイスロゴ刺繍がアクセントに。',
        now()),
        ('クラシックレザーベルト',
        'Acce',
        39600,
        true,
        '../public/img_goods/Acce_11.jpg',
        '../public/img_goods/Acce_11-2.jpg',
        '../public/img_goods/Acce_11-3.jpg',
        '../public/img_goods/Acce_11-4.jpg',
        'Acne Studiosのクラシックユニセックスベルト。ブラウンレザーを使用。<br>Acne Studiosのエングレーブロゴ入りメタルバックルがアクセントに。',
        now()),
        ('ディコンストラクテッドベルト',
        'Acce',
        49500,
        true,
        '../public/img_goods/Acce_12.jpg',
        '../public/img_goods/Acce_12-2.jpg',
        '../public/img_goods/Acce_12-3.jpg',
        '../public/img_goods/Acce_12-4.jpg',
        'Acne Studiosのディコンストラクテッドベルト。<br>ブラックのしなやかなマットカーフレザーを使用。<br>エングレーブロゴ入りメタルバックル付き。',
        now()),
        ('テディフリーストラウザーズ',
        'Bottoms',
        58300,
        true,
        '../public/img_goods/Bottoms_1.jpg',
        '../public/img_goods/Bottoms_1-2.jpg',
        '../public/img_goods/Bottoms_1-3.jpg',
        '../public/img_goods/Bottoms_1-4.jpg',
        'Acne Studiosのトラウザーズ。<br>ヘーゼルベージュのソフトなテディフリース素材を使用。<br>ドローストリングの端にロゴ入りのメタル素材を配した調節可能なウエストがポイント。<br>総裏地付き。バックパッチポケットに配した今シーズンのロゴディテールがアクセントに。長めの丈に仕立てた、レギュラーライズウエストのリラックスフィットシルエット。',
        now()),
        ('チェックトラウザーズ ユニセックス',
        'Bottoms',
        49500,
        true,
        '../public/img_goods/Bottoms_2.jpg',
        '../public/img_goods/Bottoms_2-2.jpg',
        '../public/img_goods/Bottoms_2-3.jpg',
        '../public/img_goods/Bottoms_2-4.jpg',
        'Acne Studiosのトラウザーズ。<br>全体にイエロー/ブラウンのチェックプリントを施したデザイン。<br>フロントにマイクロFaceロゴパッチ付き、バックにFaceロゴ刺繍入り。<br>サイドシームポケットとバックパッチポケット付き。',
        now()),
        ('カジュアルトラウザーズ',
        'Bottoms',
        41800,
        true,
        '../public/img_goods/Bottoms_3.jpg',
        '../public/img_goods/Bottoms_3-2.jpg',
        '../public/img_goods/Bottoms_3-3.jpg',
        '../public/img_goods/Bottoms_3-4.jpg',
        'Acne Studiosのカジュアルトラウザーズ。<br>ベージュのコットンを使用。<br>フロントプリーツを施したチノパンツスタイル。<br>アングルポケットとバックポケットがアクセントを添える、レギュラーライズウエストのレギュラーフィットスタイル。',
        now()),
        ('サテンパンツ',
        'Bottoms',
        56100,
        true,
        '../public/img_goods/Bottoms_4.jpg',
        '../public/img_goods/Bottoms_4-2.jpg',
        '../public/img_goods/Bottoms_4-3.jpg',
        '../public/img_goods/Bottoms_4-4.jpg',
        'Acne Studios のブラックトラウザーズは、余分な生地や素材だけで構成されたサテン生地で作られたストライプ パターンが特徴です。<br> 伸縮性のあるウエストバンドとリラックスフィットのカットが特徴です。',
        now()),
        ('リップストップ カーゴトラウザーズ',
        'Bottoms',
        56100,
        true,
        '../public/img_goods/Bottoms_5.jpg',
        '../public/img_goods/Bottoms_5-2.jpg',
        '../public/img_goods/Bottoms_5-3.jpg',
        '../public/img_goods/Bottoms_5-4.jpg',
        'Acne Studiosのリップストップカーゴトラウザーズ。<br>チェスナットブラウンの色合いで、コントラストを効かせるパッチワークディテールとパッチポケット、ピンクフラッグラベルを配したデザイン。<br>コットンブレンド素材を使用した、ワークウェアシルエットのリラックスフィットスタイル。',
        now()),
        ('ハイウエスト ウールブレンド テーラードトラウザーズ',
        'Bottoms',
        73700,
        true,
        '../public/img_goods/Bottoms_6.jpg',
        '../public/img_goods/Bottoms_6-2.jpg',
        '../public/img_goods/Bottoms_6-3.jpg',
        '../public/img_goods/Bottoms_6-4.jpg',
        'Acne Studiosのテーラードトラウザーズ。<br>ブラックのウール＆モヘアブレンド素材を使用。<br>ボタン付きレザーブレスがポイント。<br>ハイウエスト、丈が長めのリラックスフィットスタイル。',
        now()),
        ('ルーズフィットジーンズ ',
        'Bottoms',
        48950,
        true,
        '../public/img_goods/Bottoms_7.jpg',
        '../public/img_goods/Bottoms_7-2.jpg',
        '../public/img_goods/Bottoms_7-3.jpg',
        '../public/img_goods/Bottoms_7-4.jpg',
        'Acne Studiosのダークブルー/グリーンジーンズ。<br>ミッドウエスト、ワイドレッグ、長めの丈に仕立てたルーズフィットスタイル。<br>ファイブポケットデザイン。<br>2021ジーンズには、コットンのリジッドデニムを使用。',
        now()),
        ('フレアフィット コーデュロイジーンズ ',
        'Bottoms',
        45650,
        true,
        '../public/img_goods/Bottoms_8.jpg',
        '../public/img_goods/Bottoms_8-2.jpg',
        '../public/img_goods/Bottoms_8-3.jpg',
        '../public/img_goods/Bottoms_8-4.jpg',
        'Acne Studiosのベージュコーデュロイジーンズ。<br>ミッドライズウエストのレギュラー丈に仕立てたフレアフィットスタイル。<br>ファイブポケットデザイン。',
        now()),
        ('ストレートフィットジーンズ',
        'Bottoms',
        50050,
        true,
        '../public/img_goods/Bottoms_9.jpg',
        '../public/img_goods/Bottoms_9-2.jpg',
        '../public/img_goods/Bottoms_9-3.jpg',
        '../public/img_goods/Bottoms_9-4.jpg',
        'Acne Studiosのブルー/グリーンスリムフィットジーンズ。<br>ミッドライズウエストのレギュラー丈スタイル。<br>ファイブポケットデザイン。<br>環境にやさしい方法で栽培したリジッドデニムコットンを使用。<br>ディコンストラクテッドディテールがアクセントに。',
        now()),
        ('カジュアルスーツトラウザーズ ',
        'Bottoms',
        58300,
        true,
        '../public/img_goods/Bottoms_10.jpg',
        '../public/img_goods/Bottoms_10-2.jpg',
        '../public/img_goods/Bottoms_10-3.jpg',
        '../public/img_goods/Bottoms_10-4.jpg',
        'Acne Studiosのカジュアルスーツトラウザーズ。<br>ネイビー／ホワイトの色合いで、ベルトループにハートのチャームディテールをあしらったデザイン。<br>レギュラー丈のリラックスフィット。',
        now()),
        ('レザーパッチワーク デニムトラウザーズ',
        'Bottoms',
        211200,
        true,
        '../public/img_goods/Bottoms_11.jpg',
        '../public/img_goods/Bottoms_11-2.jpg',
        '../public/img_goods/Bottoms_11-3.jpg',
        '../public/img_goods/Bottoms_11-4.jpg',
        'Acne Studiosのトラウザーズ。<br>ダークブラウン/マルチの色合いで、レザーパッチワークがポイント。<br>ファイブポケットデザイン。<br>ミッドライズウエスト、テーパード、丈が長めのレギュラーフィットスタイル。',
        now()),
        ('レザートラウザーズ ',
        'Bottoms',
        199100,
        true,
        '../public/img_goods/Bottoms_12.jpg',
        '../public/img_goods/Bottoms_12-2.jpg',
        '../public/img_goods/Bottoms_12-3.jpg',
        '../public/img_goods/Bottoms_12-4.jpg',
        'Acne Studiosのトラウザーズ。<br>ソフトな光沢のあるコールドホワイトのレザーを使用。<br>膝上のシームディテール、サイドシームポケット、バックウェルトポケットを配して仕上げたデザイン。<br>長めの丈に仕立てた、ハイライズウエストのレギュラーフィットシルエット。',
        now()),
        ('リバーシブルダウンジャケット',
        'Outer',
        132000,
        true,
        '../public/img_goods/Outer_1.jpg',
        '../public/img_goods/Outer_1-2.jpg',
        '../public/img_goods/Outer_1-3.jpg',
        '../public/img_goods/Outer_1-4.jpg',
        'チェスナッツブラウンの色合いで、フロントセンタージッパー開閉とサイドシームポケット付き。<br>Acne Studiosのロゴパッチ、ヘムにドローコード、伸縮性のあるカフスを配して仕上げたデザイン。<br>ボリューム感のあるラグランスリーブ、レギュラー丈リラックスフィットスタイル。',
        now()),

        ('フード付きリップストップパファージャケット',
        'Outer',
        212300,
        true,
        '../public/img_goods/Outer_2.jpg',
        '../public/img_goods/Outer_2-2.jpg',
        '../public/img_goods/Outer_2-3.jpg',
        '../public/img_goods/Outer_2-4.jpg',
        'ダークカーキ/マルチの色合いで、コントラストを生み出すパッチ、フードとヘムに調節可能なドローコード付き。<br>サイドと内側にポケット、胸元にAcne Studiosラベルを配して仕上げたデザイン。<br>レギュラー丈、ボリューム感のあるレギュラーフィットスタイル。',
        now()),

        ('ルーズフィット デニムジャケット',
        'Outer',
        58300,
        true,
        '../public/img_goods/Outer_3.jpg',
        '../public/img_goods/Outer_3-2.jpg',
        '../public/img_goods/Outer_3-3.jpg',
        '../public/img_goods/Outer_3-4.jpg',
        '長めの袖と丈を配したルーズフィットスタイル。コットンのリジッドデニムを使用。',
        now()),

        ('ルースフィット デニムジャケット',
        'Outer',
        68200,
        true,
        '../public/img_goods/Outer_4.jpg',
        '../public/img_goods/Outer_4-2.jpg',
        '../public/img_goods/Outer_4-3.jpg',
        '../public/img_goods/Outer_4-4.jpg',
        'ブルー/レッドの色合いで、長めの袖と丈が特徴的な、ルーズフィットスタイル。<br>環境にやさしい方法で栽培したリジッドデニムを使用。',
        now()),

        ('リバーシブルパッチ ボンバージャケット',
        'Outer',
        90200,
        true,
        '../public/img_goods/Outer_5.jpg',
        '../public/img_goods/Outer_5-2.jpg',
        '../public/img_goods/Outer_5-3.jpg',
        '../public/img_goods/Outer_5-4.jpg',
        'アンスラサイトグレーの色合いで、キルティングの裏地付きの袖、<br>ソフトなテディ素材を使用したフロントパネル、Acne Studiosのロゴ付きパッチポケットが特徴。<br>リバーシブルサイド、ウェルトポケット、リブ編みのネックライン、<br>カフス、ヘムを配して仕上げたデザイン。ミディ丈のリラックスフィットスタイル。',
        now()),

        ('カジュアルリップストップジャケット',
        'Outer',
        81400,
        true,
        '../public/img_goods/Outer_8.jpg',
        '../public/img_goods/Outer_8-2.jpg',
        '../public/img_goods/Outer_8-3.jpg',
        '../public/img_goods/Outer_8-4.jpg',
        'ダークブルーのリサイクルポリエステルを使用。コントラストを効かせるパッチポケットがアクセントに。<br>ロゴ入りピンクフラッグラベルを配したデザイン。リラックスフィットスタイル。',
        now()),

        ('リバーシブルダウンジャケット',
        'Outer',
        132000,
        true,
        '../public/img_goods/Outer_9.jpg',
        '../public/img_goods/Outer_9-2.jpg',
        '../public/img_goods/Outer_9-3.jpg',
        '../public/img_goods/Outer_9-4.jpg',
        'ダークブルーの色合いで、フロントジッパー開閉とサイドシームポケットがポイント。<br>Acne Studiosのロゴパッチ、ヘムにドローコード、伸縮性のあるカフスを配して仕上げたデザイン。<br>ボリューム感のあるラグランスリーブ、レギュラー丈リラックスフィットスタイル。',
        now()),

        ('カジュアルリップストップジャケット ',
        'Outer',
        81400,
        true,
        '../public/img_goods/Outer_10.jpg',
        '../public/img_goods/Outer_10-2.jpg',
        '../public/img_goods/Outer_10-3.jpg',
        '../public/img_goods/Outer_10-4.jpg',
        'チェスナットブラウンのリサイクルポリエステルを使用。コントラストを効かせるパッチポケットがアクセントに。<br>ロゴ入りピンクフラッグラベルを配したデザイン。リラックスフィットスタイル。',
        now()),

        ('ウールジャケット',
        'Outer',
        135300,
        true,
        '../public/img_goods/Outer_11.jpg',
        '../public/img_goods/Outer_11-2.jpg',
        '../public/img_goods/Outer_11-3.jpg',
        '../public/img_goods/Outer_11-4.jpg',
        'ブラックのウールを使用。目立たないボタン留めとパッチポケットが特徴。<br>薄めのパッド入り、レギュラー丈のレギュラーフィットスタイル。',
        now()),

        ('シングルブレストコート',
        'Outer',
        125400,
        true,
        '../public/img_goods/Outer_12.jpg',
        '../public/img_goods/Outer_12-2.jpg',
        '../public/img_goods/Outer_12-3.jpg',
        '../public/img_goods/Outer_12-4.jpg',
        'ブラックのウールブレンド素材を使用。フロントジェットポケットと胸ポケットがポイント。<br>パッド入りショルダー、長めの袖を配して仕上げた、ロング丈のストレートレギュラーフィットスタイル。',
        now()),

        ('レザーレースアップ アンクルスニーカー',
        'Shoes',
        83600,
        true,
        '../public/img_goods/Shoes_1.jpg',
        '../public/img_goods/Shoes_1-2.jpg',
        '../public/img_goods/Shoes_1-3.jpg',
        '../public/img_goods/Shoes_1-4.jpg',
        'ハイカットのアンクル部分にゴムレザーを使用し、リップストップナイロンのトリムを組み合わせたマルチアンスラサイトの配色がポイント。<br>プラットフォームラバーソールを配し、ソールにブランドロゴをあしらったデザイン。',
        now()),

        ('ハイカットスニーカー ',
        'Shoes',
        48400,
        true,
        '../public/img_goods/Shoes_2.jpg',
        '../public/img_goods/Shoes_2-2.jpg',
        '../public/img_goods/Shoes_2-3.jpg',
        '../public/img_goods/Shoes_2-4.jpg',
        '環境にやさしい方法で栽培したコットンを使用し、ラバーソールを配したデザイン。<br>フロントにロゴ入りタグで仕上げたデザイン。',
        now()),

        ('キャンバススニーカー ',
        'Shoes',
        33000,
        true,
        '../public/img_goods/Shoes_3.jpg',
        '../public/img_goods/Shoes_3-2.jpg',
        '../public/img_goods/Shoes_3-3.jpg',
        '../public/img_goods/Shoes_3-4.jpg',
        'ブラック/オフホワイトのダメージキャンバスを使用。ラバーソール仕様。',
        now()),

        ('ローカットスニーカー ',
        'Shoes',
        59400,
        true,
        '../public/img_goods/Shoes_4.jpg',
        '../public/img_goods/Shoes_4-2.jpg',
        '../public/img_goods/Shoes_4-3.jpg',
        '../public/img_goods/Shoes_4-4.jpg',
        'ホワイト/ブラックのカーフレザーを使用。バスケットボールシューズからインスピレーションを得た一足。<br>ひび割れたような風合いに仕上げたメタリックスエードがアクセントに。',
        now()),

        ('ハイカットスニーカー',
        'Shoes',
        62700,
        true,
        '../public/img_goods/Shoes_5.jpg',
        '../public/img_goods/Shoes_5-2.jpg',
        '../public/img_goods/Shoes_5-3.jpg',
        '../public/img_goods/Shoes_5-4.jpg',
        'マルチブラックのレザーを使用。フェイスディテール付き、ラバーソールにAcne Studiosのロゴ入り。',
        now()),

        ('BOLZTER M スニーカー',
        'Shoes',
        71500,
        true,
        '../public/img_goods/Shoes_6.jpg',
        '../public/img_goods/Shoes_6-2.jpg',
        '../public/img_goods/Shoes_6-3.jpg',
        '../public/img_goods/Shoes_6-4.jpg',
        'Bolzter M ミネラルブルーは、メッシュとフェイクスエードのオーバーレイを配したスニーカー。<br>チャンキーなトレッドソール仕様。',
        now()),

        ('レースアップ アンクルブーツ',
        'Shoes',
        68200,
        true,
        '../public/img_goods/Shoes_7.jpg',
        '../public/img_goods/Shoes_7-2.jpg',
        '../public/img_goods/Shoes_7-3.jpg',
        '../public/img_goods/Shoes_7-4.jpg',
        '加硫処理を施したラバーソールが特徴で、バックにロゴディテール付き。',
        now()),

        ('レザーブーツ',
        'Shoes',
        110000,
        true,
        '../public/img_goods/Shoes_8.jpg',
        '../public/img_goods/Shoes_8-2.jpg',
        '../public/img_goods/Shoes_8-3.jpg',
        '../public/img_goods/Shoes_8-4.jpg',
        'ブラックのカーフレザーを使用。スクエアトゥ、ヒールを配したデザイン。',
        now()),

        ('レザーのスリッポンシューズ',
        'Shoes',
        83600,
        true,
        '../public/img_goods/Shoes_9.jpg',
        '../public/img_goods/Shoes_9-2.jpg',
        '../public/img_goods/Shoes_9-3.jpg',
        '../public/img_goods/Shoes_9-4.jpg',
        'スウェーデンの伝統的なビークシューズの構造を採り入れたAcne Studiosのコニャックブラウンのスリッポンミュール。<br>エンボス仕様のディテール。レザー製。シアリングインソールとプラットフォームラバーソール。',
        now()),

        ('リボンロゴ レースアップスニーカー',
        'Shoes',
        56100,
        true,
        '../public/img_goods/Shoes_10.jpg',
        '../public/img_goods/Shoes_10-2.jpg',
        '../public/img_goods/Shoes_10-3.jpg',
        '../public/img_goods/Shoes_10-4.jpg',
        'リボンロゴパターンとAcne Studiosロゴがポイント。リサイクルラバーソールを配したデザイン。',
        now()),

        ('ハイカットスニーカー',
        'Shoes',
        41800,
        true,
        '../public/img_goods/Shoes_11.jpg',
        '../public/img_goods/Shoes_11-2.jpg',
        '../public/img_goods/Shoes_11-3.jpg',
        '../public/img_goods/Shoes_11-4.jpg',
        'ペールイエロー/オフホワイトのオーガニックコットンを使用。ラバーソールを配したデザイン。タンブル仕上げ。',
        now()),

        ('BOLZTER M スニーカー',
        'Shoes',
        72600,
        true,
        '../public/img_goods/Shoes_12.jpg',
        '../public/img_goods/Shoes_12-2.jpg',
        '../public/img_goods/Shoes_12-3.jpg',
        '../public/img_goods/Shoes_12-4.jpg',
        'ダメージ感のある仕上がり。メッシュを使用し、スエードのオーバーレイとチャンキーなトレッドソールを配したデザイン。',
        now()),

        ('ロゴテープフーディ',
        'Tops',
        68200,
        true,
        '../public/img_goods/Tops_1.jpg',
        '../public/img_goods/Tops_1-2.jpg',
        '../public/img_goods/Tops_1-3.jpg',
        '../public/img_goods/Tops_1-4.jpg',
        'ブラックの環境にやさしい方法で栽培したコットンを使用、Acne Studiosのテープインサート付き。<br>リラックスフィット、リブ編みのカフスに仕上げた一着。',
        now()),

        ('ロゴクルーネック セーター',
        'Tops',
        44000,
        true,
        '../public/img_goods/Tops_2.jpg',
        '../public/img_goods/Tops_2-2.jpg',
        '../public/img_goods/Tops_2-3.jpg',
        '../public/img_goods/Tops_2-4.jpg',
        'フロントにAcne Studiosロゴ入り。リブ編みカラー、カフス、ヘムに仕上げた一着。<br>環境にやさしい方法で栽培したコットン素材の厚手フリースを使用。',
        now()),

        ('デジタルパフュームプリント Tシャツ',
        'Tops',
        30800,
        true,
        '../public/img_goods/Tops_3.jpg',
        '../public/img_goods/Tops_3-2.jpg',
        '../public/img_goods/Tops_3-3.jpg',
        '../public/img_goods/Tops_3-4.jpg',
        'ブラックの色合いで、香水のデジタルプリントとフォイルロゴプリントをあしらったアイテム。<br>環境にやさしい方法で栽培したコットンを使用した、リラックスフィットスタイル。',
        now()),

        ('ロゴテープフーディ',
        'Tops',
        68200,
        true,
        '../public/img_goods/Tops_4.jpg',
        '../public/img_goods/Tops_4-2.jpg',
        '../public/img_goods/Tops_4-3.jpg',
        '../public/img_goods/Tops_4-4.jpg',
        '環境にやさしい方法で栽培したシーブルーのコットンを使用、Acne Studiosのテープインサート付き。<br>リラックスフィット、リブ編みのカフスに仕上げた一着。',
        now()),

        ('バブルロゴ クルーネックセーター',
        'Tops',
        52800,
        true,
        '../public/img_goods/Tops_5.jpg',
        '../public/img_goods/Tops_5-2.jpg',
        '../public/img_goods/Tops_5-3.jpg',
        '../public/img_goods/Tops_5-4.jpg',
        'Acne Studiosバブルロゴ刺繍入り。リラックスフィットスタイル。環境にやさしい方法で栽培した中厚フリースコットンを使用。<br>ネックライン、カフス、ヘムをリブ編みで仕上げた一着。',
        now()),

        ('ロゴスタンプスウェットシャツ ',
        'Tops',
        44000,
        true,
        '../public/img_goods/Tops_6.jpg',
        '../public/img_goods/Tops_6-2.jpg',
        '../public/img_goods/Tops_6-3.jpg',
        '../public/img_goods/Tops_6-4.jpg',
        '環境にやさしい方法で栽培した、オイスターグレーのコットンを使用。フロントにAcne Studiosのロゴスタンプ入り。<br>リラックスフィット、リブ編みのカフスに仕上げた一着。',
        now()),

        ('コンポーザー クルーネックスウェットシャツ ',
        'Tops',
        42900,
        true,
        '../public/img_goods/Tops_7.jpg',
        '../public/img_goods/Tops_7-2.jpg',
        '../public/img_goods/Tops_7-3.jpg',
        '../public/img_goods/Tops_7-4.jpg',
        '作曲家の刺繍と、バックネックラインにあしらったフェイスロゴ刺繍がポイント。<br>環境にやさしい方法で栽培したコットンを使用。リブ編みネックラインに仕上げた、リラックスフィットスタイル。',
        now()),

        ('クルーネックスウェットシャツ',
        'Tops',
        41800,
        true,
        '../public/img_goods/Tops_8.jpg',
        '../public/img_goods/Tops_8-2.jpg',
        '../public/img_goods/Tops_8-3.jpg',
        '../public/img_goods/Tops_8-4.jpg',
        'バックにあしらったフェイスロゴパッチとフェイスロゴ刺繍がアクセントに。<br>環境にやさしい方法で栽培したコットンを使用。<br>リブ付きのネックラインがポイント。リラックスフィットスタイル。',
        now()),

         ('クルーネックスウェットシャツ',
        'Tops',
        33000,
        true,
        '../public/img_goods/Tops_9.jpg',
        '../public/img_goods/Tops_9-2.jpg',
        '../public/img_goods/Tops_9-3.jpg',
        '../public/img_goods/Tops_9-4.jpg',
        'ライトグレーメランジの色合いで、Faceロゴパッチがアクセントに。コットンを使用。<br>ネックライン、カフス、ヘムはリブ編み仕上げ。',
        now()),

         ('FACEロゴ クルーネックセーター',
        'Tops',
        63800,
        true,
        '../public/img_goods/Tops_10.jpg',
        '../public/img_goods/Tops_10-2.jpg',
        '../public/img_goods/Tops_10-3.jpg',
        '../public/img_goods/Tops_10-4.jpg',
        'スペアミントグリーン/サファイアブルーの色合いで、クロスボーンFaceロゴとアローパターンをあしらったデザイン。<br>ネックライン、カフス、ヘムはリブ編み仕上げ。マイクロFaceロゴパッチがアクセントに。<br>ウール＆コットンブレンド素材を使用。レギュラー丈のリラックスフィットスタイル。',
        now()),

         ('ロゴTシャツ ',
        'Tops',
        29700,
        true,
        '../public/img_goods/Tops_11.jpg',
        '../public/img_goods/Tops_11-2.jpg',
        '../public/img_goods/Tops_11-3.jpg',
        '../public/img_goods/Tops_11-4.jpg',
        '環境にやさしい方法で栽培した、オイスターグレーのコットンを使用。フロントセンターにブランドロゴ入り。',
        now()),

         ('コンポーザー クルーネックTシャツ',
        'Tops',
        24200,
        true,
        '../public/img_goods/Tops_12.jpg',
        '../public/img_goods/Tops_12-2.jpg',
        '../public/img_goods/Tops_12-3.jpg',
        '../public/img_goods/Tops_12-4.jpg',
        '環境にやさしい方法で栽培した、コーヒーブラウンのコットンを使用。胸元に大きなコンポーザープリント入り。',
        now());
