INSERT INTO `goods`
(`goods_name`, `goods_tag`, `goods_price`, `goods_flg`, `goods_imgurl1`, `goods_imgurl2`, `goods_imgurl3`, `goods_imgurl4`,`goods_detail`, `goods_createdate`)
VALUES ('リバーシブルダウンジャケット',
        'Outer',
        132000,
        true,
        '../public/img_goods/Outer_1.jpg',
        '../public/img_goods/Outer_1-2.jpg',
        '../public/img_goods/Outer_1-3.jpg',
        '../public/img_goods/Outer_1-4.jpg',
        'チェスナッツブラウンの色合いで、フロントセンタージッパー開閉とサイドシームポケット付き。<br>Acne Studiosのロゴパッチ、ヘムにドローコード、伸縮性のあるカフスを配して仕上げたデザイン。<br>ボリューム感のあるラグランスリーブ、レギュラー丈リラックスフィットスタイル。',
        now()),

        ('フード付きリップストップパファージャケット',
        'Outer',
        212300,
        true,
        '../public/img_goods/Outer_2.jpg',
        '../public/img_goods/Outer_2-2.jpg',
        '../public/img_goods/Outer_2-3.jpg',
        '../public/img_goods/Outer_2-4.jpg',
        'ダークカーキ/マルチの色合いで、コントラストを生み出すパッチ、フードとヘムに調節可能なドローコード付き。<br>サイドと内側にポケット、胸元にAcne Studiosラベルを配して仕上げたデザイン。<br>レギュラー丈、ボリューム感のあるレギュラーフィットスタイル。',
        now()),

        ('ルーズフィット デニムジャケット',
        'Outer',
        58300,
        true,
        '../public/img_goods/Outer_3.jpg',
        '../public/img_goods/Outer_3-2.jpg',
        '../public/img_goods/Outer_3-3.jpg',
        '../public/img_goods/Outer_3-4.jpg',
        '長めの袖と丈を配したルーズフィットスタイル。コットンのリジッドデニムを使用。',
        now()),

        ('ルースフィット デニムジャケット',
        'Outer',
        68200,
        true,
        '../public/img_goods/Outer_4.jpg',
        '../public/img_goods/Outer_4-2.jpg',
        '../public/img_goods/Outer_4-3.jpg',
        '../public/img_goods/Outer_4-4.jpg',
        'ブルー/レッドの色合いで、長めの袖と丈が特徴的な、ルーズフィットスタイル。<br>環境にやさしい方法で栽培したリジッドデニムを使用。',
        now()),

        ('リバーシブルパッチ ボンバージャケット',
        'Outer',
        90200,
        true,
        '../public/img_goods/Outer_5.jpg',
        '../public/img_goods/Outer_5-2.jpg',
        '../public/img_goods/Outer_5-3.jpg',
        '../public/img_goods/Outer_5-4.jpg',
        'アンスラサイトグレーの色合いで、キルティングの裏地付きの袖、<br>ソフトなテディ素材を使用したフロントパネル、Acne Studiosのロゴ付きパッチポケットが特徴。<br>リバーシブルサイド、ウェルトポケット、リブ編みのネックライン、<br>カフス、ヘムを配して仕上げたデザイン。ミディ丈のリラックスフィットスタイル。',
        now()),

        ('カジュアルリップストップジャケット',
        'Outer',
        81400,
        true,
        '../public/img_goods/Outer_8.jpg',
        '../public/img_goods/Outer_8-2.jpg',
        '../public/img_goods/Outer_8-3.jpg',
        '../public/img_goods/Outer_8-4.jpg',
        'ダークブルーのリサイクルポリエステルを使用。コントラストを効かせるパッチポケットがアクセントに。<br>ロゴ入りピンクフラッグラベルを配したデザイン。リラックスフィットスタイル。',
        now()),

        ('リバーシブルダウンジャケット',
        'Outer',
        132000,
        true,
        '../public/img_goods/Outer_9.jpg',
        '../public/img_goods/Outer_9-2.jpg',
        '../public/img_goods/Outer_9-3.jpg',
        '../public/img_goods/Outer_9-4.jpg',
        'ダークブルーの色合いで、フロントジッパー開閉とサイドシームポケットがポイント。<br>Acne Studiosのロゴパッチ、ヘムにドローコード、伸縮性のあるカフスを配して仕上げたデザイン。<br>ボリューム感のあるラグランスリーブ、レギュラー丈リラックスフィットスタイル。',
        now()),

        ('カジュアルリップストップジャケット ',
        'Outer',
        81400,
        true,
        '../public/img_goods/Outer_10.jpg',
        '../public/img_goods/Outer_10-2.jpg',
        '../public/img_goods/Outer_10-3.jpg',
        '../public/img_goods/Outer_10-4.jpg',
        'チェスナットブラウンのリサイクルポリエステルを使用。コントラストを効かせるパッチポケットがアクセントに。<br>ロゴ入りピンクフラッグラベルを配したデザイン。リラックスフィットスタイル。',
        now()),

        ('ウールジャケット',
        'Outer',
        135300,
        true,
        '../public/img_goods/Outer_11.jpg',
        '../public/img_goods/Outer_11-2.jpg',
        '../public/img_goods/Outer_11-3.jpg',
        '../public/img_goods/Outer_11-4.jpg',
        'ブラックのウールを使用。目立たないボタン留めとパッチポケットが特徴。<br>薄めのパッド入り、レギュラー丈のレギュラーフィットスタイル。',
        now()),

        ('シングルブレストコート',
        'Outer',
        125400,
        true,
        '../public/img_goods/Outer_12.jpg',
        '../public/img_goods/Outer_12-2.jpg',
        '../public/img_goods/Outer_12-3.jpg',
        '../public/img_goods/Outer_12-4.jpg',
        'ブラックのウールブレンド素材を使用。フロントジェットポケットと胸ポケットがポイント。<br>パッド入りショルダー、長めの袖を配して仕上げた、ロング丈のストレートレギュラーフィットスタイル。',
        now()),

        ('レザーレースアップ アンクルスニーカー',
        'Shoes',
        83600,
        true,
        '../public/img_goods/Shoes_1.jpg',
        '../public/img_goods/Shoes_1-2.jpg',
        '../public/img_goods/Shoes_1-3.jpg',
        '../public/img_goods/Shoes_1-4.jpg',
        'ハイカットのアンクル部分にゴムレザーを使用し、リップストップナイロンのトリムを組み合わせたマルチアンスラサイトの配色がポイント。<br>プラットフォームラバーソールを配し、ソールにブランドロゴをあしらったデザイン。',
        now()),

        ('ハイカットスニーカー ',
        'Shoes',
        48400,
        true,
        '../public/img_goods/Shoes_2.jpg',
        '../public/img_goods/Shoes_2-2.jpg',
        '../public/img_goods/Shoes_2-3.jpg',
        '../public/img_goods/Shoes_2-4.jpg',
        '環境にやさしい方法で栽培したコットンを使用し、ラバーソールを配したデザイン。<br>フロントにロゴ入りタグで仕上げたデザイン。',
        now()),

        ('キャンバススニーカー ',
        'Shoes',
        33000,
        true,
        '../public/img_goods/Shoes_3.jpg',
        '../public/img_goods/Shoes_3-2.jpg',
        '../public/img_goods/Shoes_3-3.jpg',
        '../public/img_goods/Shoes_3-4.jpg',
        'ブラック/オフホワイトのダメージキャンバスを使用。ラバーソール仕様。',
        now()),

        ('ローカットスニーカー ',
        'Shoes',
        59400,
        true,
        '../public/img_goods/Shoes_4.jpg',
        '../public/img_goods/Shoes_4-2.jpg',
        '../public/img_goods/Shoes_4-3.jpg',
        '../public/img_goods/Shoes_4-4.jpg',
        'ホワイト/ブラックのカーフレザーを使用。バスケットボールシューズからインスピレーションを得た一足。<br>ひび割れたような風合いに仕上げたメタリックスエードがアクセントに。',
        now()),

        ('ハイカットスニーカー',
        'Shoes',
        62700,
        true,
        '../public/img_goods/Shoes_5.jpg',
        '../public/img_goods/Shoes_5-2.jpg',
        '../public/img_goods/Shoes_5-3.jpg',
        '../public/img_goods/Shoes_5-4.jpg',
        'マルチブラックのレザーを使用。フェイスディテール付き、ラバーソールにAcne Studiosのロゴ入り。',
        now()),

        ('BOLZTER M スニーカー',
        'Shoes',
        71500,
        true,
        '../public/img_goods/Shoes_6.jpg',
        '../public/img_goods/Shoes_6-2.jpg',
        '../public/img_goods/Shoes_6-3.jpg',
        '../public/img_goods/Shoes_6-4.jpg',
        'Bolzter M ミネラルブルーは、メッシュとフェイクスエードのオーバーレイを配したスニーカー。<br>チャンキーなトレッドソール仕様。',
        now()),

        ('レースアップ アンクルブーツ',
        'Shoes',
        68200,
        true,
        '../public/img_goods/Shoes_7.jpg',
        '../public/img_goods/Shoes_7-2.jpg',
        '../public/img_goods/Shoes_7-3.jpg',
        '../public/img_goods/Shoes_7-4.jpg',
        '加硫処理を施したラバーソールが特徴で、バックにロゴディテール付き。',
        now()),

        ('レザーブーツ',
        'Shoes',
        110000,
        true,
        '../public/img_goods/Shoes_8.jpg',
        '../public/img_goods/Shoes_8-2.jpg',
        '../public/img_goods/Shoes_8-3.jpg',
        '../public/img_goods/Shoes_8-4.jpg',
        'ブラックのカーフレザーを使用。スクエアトゥ、ヒールを配したデザイン。',
        now()),

        ('レザーのスリッポンシューズ',
        'Shoes',
        83600,
        true,
        '../public/img_goods/Shoes_9.jpg',
        '../public/img_goods/Shoes_9-2.jpg',
        '../public/img_goods/Shoes_9-3.jpg',
        '../public/img_goods/Shoes_9-4.jpg',
        'スウェーデンの伝統的なビークシューズの構造を採り入れたAcne Studiosのコニャックブラウンのスリッポンミュール。<br>エンボス仕様のディテール。レザー製。シアリングインソールとプラットフォームラバーソール。',
        now()),

        ('リボンロゴ レースアップスニーカー',
        'Shoes',
        56100,
        true,
        '../public/img_goods/Shoes_10.jpg',
        '../public/img_goods/Shoes_10-2.jpg',
        '../public/img_goods/Shoes_10-3.jpg',
        '../public/img_goods/Shoes_10-4.jpg',
        'リボンロゴパターンとAcne Studiosロゴがポイント。リサイクルラバーソールを配したデザイン。',
        now()),

        ('ハイカットスニーカー',
        'Shoes',
        41800,
        true,
        '../public/img_goods/Shoes_11.jpg',
        '../public/img_goods/Shoes_11-2.jpg',
        '../public/img_goods/Shoes_11-3.jpg',
        '../public/img_goods/Shoes_11-4.jpg',
        'ペールイエロー/オフホワイトのオーガニックコットンを使用。ラバーソールを配したデザイン。タンブル仕上げ。',
        now()),

        ('BOLZTER M スニーカー',
        'Shoes',
        72600,
        true,
        '../public/img_goods/Shoes_12.jpg',
        '../public/img_goods/Shoes_12-2.jpg',
        '../public/img_goods/Shoes_12-3.jpg',
        '../public/img_goods/Shoes_12-4.jpg',
        'ダメージ感のある仕上がり。メッシュを使用し、スエードのオーバーレイとチャンキーなトレッドソールを配したデザイン。',
        now()),

        ('ロゴテープフーディ',
        'Tops',
        68200,
        true,
        '../public/img_goods/Tops_1.jpg',
        '../public/img_goods/Tops_1-2.jpg',
        '../public/img_goods/Tops_1-3.jpg',
        '../public/img_goods/Tops_1-4.jpg',
        'ブラックの環境にやさしい方法で栽培したコットンを使用、Acne Studiosのテープインサート付き。<br>リラックスフィット、リブ編みのカフスに仕上げた一着。',
        now()),

        ('ロゴクルーネック セーター',
        'Tops',
        44000,
        true,
        '../public/img_goods/Tops_2.jpg',
        '../public/img_goods/Tops_2-2.jpg',
        '../public/img_goods/Tops_2-3.jpg',
        '../public/img_goods/Tops_2-4.jpg',
        'フロントにAcne Studiosロゴ入り。リブ編みカラー、カフス、ヘムに仕上げた一着。<br>環境にやさしい方法で栽培したコットン素材の厚手フリースを使用。',
        now()),

        ('デジタルパフュームプリント Tシャツ',
        'Tops',
        30800,
        true,
        '../public/img_goods/Tops_3.jpg',
        '../public/img_goods/Tops_3-2.jpg',
        '../public/img_goods/Tops_3-3.jpg',
        '../public/img_goods/Tops_3-4.jpg',
        'ブラックの色合いで、香水のデジタルプリントとフォイルロゴプリントをあしらったアイテム。<br>環境にやさしい方法で栽培したコットンを使用した、リラックスフィットスタイル。',
        now()),

        ('ロゴテープフーディ',
        'Tops',
        68200,
        true,
        '../public/img_goods/Tops_4.jpg',
        '../public/img_goods/Tops_4-2.jpg',
        '../public/img_goods/Tops_4-3.jpg',
        '../public/img_goods/Tops_4-4.jpg',
        '環境にやさしい方法で栽培したシーブルーのコットンを使用、Acne Studiosのテープインサート付き。<br>リラックスフィット、リブ編みのカフスに仕上げた一着。',
        now()),

        ('バブルロゴ クルーネックセーター',
        'Tops',
        52800,
        true,
        '../public/img_goods/Tops_5.jpg',
        '../public/img_goods/Tops_5-2.jpg',
        '../public/img_goods/Tops_5-3.jpg',
        '../public/img_goods/Tops_5-4.jpg',
        'Acne Studiosバブルロゴ刺繍入り。リラックスフィットスタイル。環境にやさしい方法で栽培した中厚フリースコットンを使用。<br>ネックライン、カフス、ヘムをリブ編みで仕上げた一着。',
        now()),

        ('ロゴスタンプスウェットシャツ ',
        'Tops',
        44000,
        true,
        '../public/img_goods/Tops_6.jpg',
        '../public/img_goods/Tops_6-2.jpg',
        '../public/img_goods/Tops_6-3.jpg',
        '../public/img_goods/Tops_6-4.jpg',
        '環境にやさしい方法で栽培した、オイスターグレーのコットンを使用。フロントにAcne Studiosのロゴスタンプ入り。<br>リラックスフィット、リブ編みのカフスに仕上げた一着。',
        now()),

        ('コンポーザー クルーネックスウェットシャツ ',
        'Tops',
        42900,
        true,
        '../public/img_goods/Tops_7.jpg',
        '../public/img_goods/Tops_7-2.jpg',
        '../public/img_goods/Tops_7-3.jpg',
        '../public/img_goods/Tops_7-4.jpg',
        '作曲家の刺繍と、バックネックラインにあしらったフェイスロゴ刺繍がポイント。<br>環境にやさしい方法で栽培したコットンを使用。リブ編みネックラインに仕上げた、リラックスフィットスタイル。',
        now()),

        ('クルーネックスウェットシャツ',
        'Tops',
        41800,
        true,
        '../public/img_goods/Tops_8.jpg',
        '../public/img_goods/Tops_8-2.jpg',
        '../public/img_goods/Tops_8-3.jpg',
        '../public/img_goods/Tops_8-4.jpg',
        'バックにあしらったフェイスロゴパッチとフェイスロゴ刺繍がアクセントに。<br>環境にやさしい方法で栽培したコットンを使用。<br>リブ付きのネックラインがポイント。リラックスフィットスタイル。',
        now()),

         ('クルーネックスウェットシャツ',
        'Tops',
        33000,
        true,
        '../public/img_goods/Tops_9.jpg',
        '../public/img_goods/Tops_9-2.jpg',
        '../public/img_goods/Tops_9-3.jpg',
        '../public/img_goods/Tops_9-4.jpg',
        'ライトグレーメランジの色合いで、Faceロゴパッチがアクセントに。コットンを使用。<br>ネックライン、カフス、ヘムはリブ編み仕上げ。',
        now()),

         ('FACEロゴ クルーネックセーター',
        'Tops',
        63800,
        true,
        '../public/img_goods/Tops_10.jpg',
        '../public/img_goods/Tops_10-2.jpg',
        '../public/img_goods/Tops_10-3.jpg',
        '../public/img_goods/Tops_10-4.jpg',
        'スペアミントグリーン/サファイアブルーの色合いで、クロスボーンFaceロゴとアローパターンをあしらったデザイン。<br>ネックライン、カフス、ヘムはリブ編み仕上げ。マイクロFaceロゴパッチがアクセントに。<br>ウール＆コットンブレンド素材を使用。レギュラー丈のリラックスフィットスタイル。',
        now()),

         ('ロゴTシャツ ',
        'Tops',
        29700,
        true,
        '../public/img_goods/Tops_11.jpg',
        '../public/img_goods/Tops_11-2.jpg',
        '../public/img_goods/Tops_11-3.jpg',
        '../public/img_goods/Tops_11-4.jpg',
        '環境にやさしい方法で栽培した、オイスターグレーのコットンを使用。フロントセンターにブランドロゴ入り。',
        now()),

         ('コンポーザー クルーネックTシャツ',
        'Tops',
        24200,
        true,
        '../public/img_goods/Tops_12.jpg',
        '../public/img_goods/Tops_12-2.jpg',
        '../public/img_goods/Tops_12-3.jpg',
        '../public/img_goods/Tops_12-4.jpg',
        '環境にやさしい方法で栽培した、コーヒーブラウンのコットンを使用。胸元に大きなコンポーザープリント入り。',
        now());
