INSERT INTO `goods`
(`goods_name`, `goods_tag`, `goods_price`, `goods_flg`, `goods_imgurl1`, `goods_imgurl2`, `goods_imgurl3`, `goods_imgurl4`,`goods_detail`, `goods_createdate`)
VALUES ('ライトウールスカーフ - オーバーサイズ',
        'Acce',
        28600,
        true,
        '../public/img_goods/Acce_1.jpg',
        '../public/img_goods/Acce_1-2.jpg',
        '../public/img_goods/Acce_1-3.jpg',
        '../public/img_goods/Acce_1-4.jpg',
        'Acne Studiosのスカーフ。<br>ライトグレーメランジのソフトな薄手ウールを使用。<br>両端に控えめなフリンジ付き、Acne Studiosのラベルがアクセントに。',
        now()),
('フリンジウールスカーフ - オーバーサイズ',
        'Acce',
        26950,
        true,
        '../public/img_goods/Acce_2.jpg',
        '../public/img_goods/Acce_2-2.jpg',
        '../public/img_goods/Acce_2-3.jpg',
        '../public/img_goods/Acce_2-4.jpg',
        'Acne Studiosのフリンジスカーフ。<br>ライトオリーブメランジの中厚ウールを使用。<br>Acne Studiosのピンクラベルがアクセントに。',
        now()),
('フリンジウールスカーフ - スキニー',
        'Acce',
        17050,
        true,
        '../public/img_goods/Acce_3.jpg',
        '../public/img_goods/Acce_3-2.jpg',
        '../public/img_goods/Acce_3-3.jpg',
        '../public/img_goods/Acce_3-4.jpg',
        'Acne Studiosのフリンジスカーフ。<br>ネイビーブルーの中厚ウールを使用。<br>Acne Studiosのピンクラベルがアクセントに。',
        now()),
('フリンジウールスカーフ - ナロー ',
        'Acce',
        21450,
        true,
        '../public/img_goods/Acce_4.jpg',
        '../public/img_goods/Acce_4-2.jpg',
        '../public/img_goods/Acce_4-3.jpg',
        '../public/img_goods/Acce_4-4.jpg',
        'Acne Studiosのフリンジスカーフ。<br>キャラメルブラウンの中厚ウールを使用。<br>Acne Studiosのピンクラベルがアクセントに。',
        now()),
('チェックウールスカーフ ',
        'Acce',
        24200,
        true,
        '../public/img_goods/Acce_5.jpg',
        '../public/img_goods/Acce_5-2.jpg',
        '../public/img_goods/Acce_5-3.jpg',
        '../public/img_goods/Acce_5-4.jpg',
        'Acne Studiosのウールスカーフ。<br>グレー/ブラック/ホワイトのチェック柄をあしらったデザイン。<br>洗濯表示ラベルのプリント入り。',
        now()),
('タフテッドウールブレンドスカーフ',
        'Acce',
        44000,
        true,
        '../public/img_goods/Acce_6.jpg',
        '../public/img_goods/Acce_6-2.jpg',
        '../public/img_goods/Acce_6-3.jpg',
        '../public/img_goods/Acce_6-4.jpg',
        'Acne Studiosのニットスカーフ。<br>ソフトでふんわりとした風合いに仕上げたチョコレートブラウンのタフテッドウールブレンド素材を使用。<br>Acne Studiosのロゴラベルがアクセントに。',
        now()),
('スモールFACEロゴビーニー',
        'Acce',
        19800,
        true,
        '../public/img_goods/Acce_7.jpg',
        '../public/img_goods/Acce_7-2.jpg',
        '../public/img_goods/Acce_7-3.jpg',
        '../public/img_goods/Acce_7-4.jpg',
        'Acne Studiosのニットビーニー。<br>パープルメランジのチャンキーウールを使用。<br>小さなFaceロゴパッチ刺繍とリブ編みディテールがアクセントに。',
        now()),
('スモールFACEロゴビーニー',
        'Acce',
        17050,
        true,
        '../public/img_goods/Acce_8.jpg',
        '../public/img_goods/Acce_8-2.jpg',
        '../public/img_goods/Acce_8-3.jpg',
        '../public/img_goods/Acce_8-4.jpg',
        'Acne Studiosのニットビーニー。<br>グレーメランジのチャンキーウールを使用。<br>小さなFaceロゴパッチ刺繍とリブ編みディテールがアクセントに。',
        now()),
('コットン ベースボールキャップ',
        'Acce',
        17050,
        true,
        '../public/img_goods/Acce_9.jpg',
        '../public/img_goods/Acce_9-2.jpg',
        '../public/img_goods/Acce_9-3.jpg',
        '../public/img_goods/Acce_9-4.jpg',
        'Acne Studiosのベースボールキャップ<br>。フォレストグリーンの色合いで、フローラルパターン入りライニングがコントラストを効かせるシックスパネルデザイン。<br>ヘッドバンドに配した調節可能なビニールストラップ、アイレット、マイクロフェイスパッチがアクセントに。<br>主な素材にリサイクルポリエステルと環境にやさしい方法で栽培したコットンを使用。',
        now()),
('フランネルバケットハット',
        'Acce',
        18700,
        true,
        '../public/img_goods/Acce_10.jpg',
        '../public/img_goods/Acce_10-2.jpg',
        '../public/img_goods/Acce_10-3.jpg',
        '../public/img_goods/Acce_10-4.jpg',
        'Acne Studiosのバケットハット。<br>オプティックホワイト/ブラックの起毛仕上げフランネル素材を使用した、チェッカーデザイン。<br>環境にやさしい方法で栽培したコットンを使用。<br>フェイスロゴ刺繍パッチとフェイスロゴ刺繍がアクセントに。',
        now()),
('クラシックレザーベルト',
        'Acce',
        39600,
        true,
        '../public/img_goods/Acce_11.jpg',
        '../public/img_goods/Acce_11-2.jpg',
        '../public/img_goods/Acce_11-3.jpg',
        '../public/img_goods/Acce_11-4.jpg',
        'Acne Studiosのクラシックユニセックスベルト。ブラウンレザーを使用。<br>Acne Studiosのエングレーブロゴ入りメタルバックルがアクセントに。',
        now()),
('ディコンストラクテッドベルト',
        'Acce',
        49500,
        true,
        '../public/img_goods/Acce_12.jpg',
        '../public/img_goods/Acce_12-2.jpg',
        '../public/img_goods/Acce_12-3.jpg',
        '../public/img_goods/Acce_12-4.jpg',
        'Acne Studiosのディコンストラクテッドベルト。<br>ブラックのしなやかなマットカーフレザーを使用。<br>エングレーブロゴ入りメタルバックル付き。',
        now()),
('テディフリーストラウザーズ',
        'Bottoms',
        58300,
        true,
        '../public/img_goods/Bottoms_1.jpg',
        '../public/img_goods/Bottoms_1-2.jpg',
        '../public/img_goods/Bottoms_1-3.jpg',
        '../public/img_goods/Bottoms_1-4.jpg',
        'Acne Studiosのトラウザーズ。<br>ヘーゼルベージュのソフトなテディフリース素材を使用。<br>ドローストリングの端にロゴ入りのメタル素材を配した調節可能なウエストがポイント。<br>総裏地付き。バックパッチポケットに配した今シーズンのロゴディテールがアクセントに。長めの丈に仕立てた、レギュラーライズウエストのリラックスフィットシルエット。',
        now()),
('チェックトラウザーズ ユニセックス',
        'Bottoms',
        49500,
        true,
        '../public/img_goods/Bottoms_2.jpg',
        '../public/img_goods/Bottoms_2-2.jpg',
        '../public/img_goods/Bottoms_2-3.jpg',
        '../public/img_goods/Bottoms_2-4.jpg',
        'Acne Studiosのトラウザーズ。<br>全体にイエロー/ブラウンのチェックプリントを施したデザイン。<br>フロントにマイクロFaceロゴパッチ付き、バックにFaceロゴ刺繍入り。<br>サイドシームポケットとバックパッチポケット付き。',
        now()),
('カジュアルトラウザーズ',
        'Bottoms',
        41800,
        true,
        '../public/img_goods/Bottoms_3.jpg',
        '../public/img_goods/Bottoms_3-2.jpg',
        '../public/img_goods/Bottoms_3-3.jpg',
        '../public/img_goods/Bottoms_3-4.jpg',
        'Acne Studiosのカジュアルトラウザーズ。<br>ベージュのコットンを使用。<br>フロントプリーツを施したチノパンツスタイル。<br>アングルポケットとバックポケットがアクセントを添える、レギュラーライズウエストのレギュラーフィットスタイル。',
        now()),
('サテンパンツ',
        'Bottoms',
        56100,
        true,
        '../public/img_goods/Bottoms_4.jpg',
        '../public/img_goods/Bottoms_4-2.jpg',
        '../public/img_goods/Bottoms_4-3.jpg',
        '../public/img_goods/Bottoms_4-4.jpg',
        'Acne Studios のブラックトラウザーズは、余分な生地や素材だけで構成されたサテン生地で作られたストライプ パターンが特徴です。<br> 伸縮性のあるウエストバンドとリラックスフィットのカットが特徴です。',
        now()),
('リップストップ カーゴトラウザーズ',
        'Bottoms',
        56100,
        true,
        '../public/img_goods/Bottoms_5.jpg',
        '../public/img_goods/Bottoms_5-2.jpg',
        '../public/img_goods/Bottoms_5-3.jpg',
        '../public/img_goods/Bottoms_5-4.jpg',
        'Acne Studiosのリップストップカーゴトラウザーズ。<br>チェスナットブラウンの色合いで、コントラストを効かせるパッチワークディテールとパッチポケット、ピンクフラッグラベルを配したデザイン。<br>コットンブレンド素材を使用した、ワークウェアシルエットのリラックスフィットスタイル。',
        now()),
('ハイウエスト ウールブレンド テーラードトラウザーズ',
        'Bottoms',
        73700,
        true,
        '../public/img_goods/Bottoms_6.jpg',
        '../public/img_goods/Bottoms_6-2.jpg',
        '../public/img_goods/Bottoms_6-3.jpg',
        '../public/img_goods/Bottoms_6-4.jpg',
        'Acne Studiosのテーラードトラウザーズ。<br>ブラックのウール＆モヘアブレンド素材を使用。<br>ボタン付きレザーブレスがポイント。<br>ハイウエスト、丈が長めのリラックスフィットスタイル。',
        now()),
('ルーズフィットジーンズ ',
        'Bottoms',
        48950,
        true,
        '../public/img_goods/Bottoms_7.jpg',
        '../public/img_goods/Bottoms_7-2.jpg',
        '../public/img_goods/Bottoms_7-3.jpg',
        '../public/img_goods/Bottoms_7-4.jpg',
        'Acne Studiosのダークブルー/グリーンジーンズ。<br>ミッドウエスト、ワイドレッグ、長めの丈に仕立てたルーズフィットスタイル。<br>ファイブポケットデザイン。<br>2021ジーンズには、コットンのリジッドデニムを使用。',
        now()),
('フレアフィット コーデュロイジーンズ ',
        'Bottoms',
        45650,
        true,
        '../public/img_goods/Bottoms_8.jpg',
        '../public/img_goods/Bottoms_8-2.jpg',
        '../public/img_goods/Bottoms_8-3.jpg',
        '../public/img_goods/Bottoms_8-4.jpg',
        'Acne Studiosのベージュコーデュロイジーンズ。<br>ミッドライズウエストのレギュラー丈に仕立てたフレアフィットスタイル。<br>ファイブポケットデザイン。',
        now()),
('ストレートフィットジーンズ',
        'Bottoms',
        50050,
        true,
        '../public/img_goods/Bottoms_9.jpg',
        '../public/img_goods/Bottoms_9-2.jpg',
        '../public/img_goods/Bottoms_9-3.jpg',
        '../public/img_goods/Bottoms_9-4.jpg',
        'Acne Studiosのブルー/グリーンスリムフィットジーンズ。<br>ミッドライズウエストのレギュラー丈スタイル。<br>ファイブポケットデザイン。<br>環境にやさしい方法で栽培したリジッドデニムコットンを使用。<br>ディコンストラクテッドディテールがアクセントに。',
        now()),
('カジュアルスーツトラウザーズ ',
        'Bottoms',
        58300,
        true,
        '../public/img_goods/Bottoms_10.jpg',
        '../public/img_goods/Bottoms_10-2.jpg',
        '../public/img_goods/Bottoms_10-3.jpg',
        '../public/img_goods/Bottoms_10-4.jpg',
        'Acne Studiosのカジュアルスーツトラウザーズ。<br>ネイビー／ホワイトの色合いで、ベルトループにハートのチャームディテールをあしらったデザイン。<br>レギュラー丈のリラックスフィット。',
        now()),
('レザーパッチワーク デニムトラウザーズ',
        'Bottoms',
        211200,
        true,
        '../public/img_goods/Bottoms_11.jpg',
        '../public/img_goods/Bottoms_11-2.jpg',
        '../public/img_goods/Bottoms_11-3.jpg',
        '../public/img_goods/Bottoms_11-4.jpg',
        'Acne Studiosのトラウザーズ。<br>ダークブラウン/マルチの色合いで、レザーパッチワークがポイント。<br>ファイブポケットデザイン。<br>ミッドライズウエスト、テーパード、丈が長めのレギュラーフィットスタイル。',
        now()),
('レザートラウザーズ ',
        'Bottoms',
        199100,
        true,
        '../public/img_goods/Bottoms_12.jpg',
        '../public/img_goods/Bottoms_12-2.jpg',
        '../public/img_goods/Bottoms_12-3.jpg',
        '../public/img_goods/Bottoms_12-4.jpg',
        'Acne Studiosのトラウザーズ。<br>ソフトな光沢のあるコールドホワイトのレザーを使用。<br>膝上のシームディテール、サイドシームポケット、バックウェルトポケットを配して仕上げたデザイン。<br>長めの丈に仕立てた、ハイライズウエストのレギュラーフィットシルエット。',
        now());